### PR TITLE
Edits to NOT-YOU, questions to LEAP SMEAR

### PR DESCRIPTION
**Pull request by goldbe**
Harlan, Again I am asking for write access to our repository for our draft. In the meantime here are my proposed changes.

Our draft will expire in less than 24 hours, so I plan to submit this version shortly to the IETF datatracker. I'm going to IETF102 and can push this draft then.

You are welcome to make your own edits to this and submit the updated version to the datatracker once you have them.

### CODE REVIEW

**Comment by goldbe** [comment]
Here is the link to compile this:

https://xml2rfc.tools.ietf.org/cgi-bin/xml2rfc.cgi?input=&url=https://raw.githubusercontent.com/goldbe/ietf-ntp-refid-updates/a956ac96983ec0cb482dbfa2f583356f628f6dfb/ntp-refid-updates.xml&modeAsFormat=txt/ascii&type=toframe&Submit=Submit

**Comment by goldbe** [comment]
@hstenn I've just submitted -03 to the datatracker. Please feel free to make more edits and submit -04.  I wanted to do this before the draft expired.  Thanks.

**Comment by mburnicki** [comment]
@goldbe Sharon, section 1.4 about the Leap-Smear REFID says:

`While the proper handling of leap seconds can be expected from up-to-date software and time servers, there are large numbers of out-of-date software installations and systems that are just not able to properly handle a leap second correction.`

Just a quick note to make things clearer:

Most protocols and implementations like ntpd have been able to handle leap seconds properly for a long time. The main problem is that the tools like ntpd can only pass the leap second announcement on to the underlying  operating system, which then inserts the leap second at the right point in time.

Unfortunately, most OS kernels for simplicity just step the time back by 1 s to insert the leap second, which is not a bug but by design, even though this time step is what causes lots of problems with applications that just observe that the system time suddenly steps back.

It doesn't make a difference if a leap second announcement is received and passed to the kernel via e.g. the NTP or the PTP protocol.

Leap smearing is one possibility to prevent the OS kernel from stepping the time. See also:

"Leap Second Smearing with NTP"
https://www.meinbergglobal.com/download/burnicki/Leap%20Second%20Smearing%20With%20NTP.pdf

and maybe some other related whitepapers at
https://www.meinbergglobal.com/english/info/#whitepaper

**Comment by goldbe** [comment]
Thanks, @mburnicki.

You should probably discuss this point with @hstenn, since my contributions to the draft are mainly the NOT-YOU REFID and it's implications on security. I don't have a strong opinion on the leap smear REFID, I'm mainly providing editorial comments on leap smear to @hstenn who wrote that section.

**Comment by hstenn** [comment]
@goldbe, what do I need to do to get you write access?  I made you a collaborator here a while ago, and that's the only option I've seen when digging thru that stuff.

**Pull request merged**
